version: '2'
services:
  vscode:
    image: jr-app-vscode
    environment:
      - DISPLAY_WIDTH=1280
      - DISPLAY_HEIGHT=720
      - KEEP_APP_RUNNING-1
    privileged: true
    cap_add: 
      - "ALL"
      - "CAP_SYS_ADMIN"
    volumes:
      - ~/vscode:/app/:rw
    ports:
      - 8001:5800
    user: root